name: Pull Request Notification
on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Show custom message and GIF
        run: |
          echo "Hello, PR maker! We have received your pull request."
          git commit -m "Add GIF to PR notification message"
          git push origin HEAD:$GITHUB_REF
